baseurl: /louisville
permalink: pretty
markdown: kramdown
paginate: 5
repo: louisville
github_org: maptime
maptime:
  chapter: Maptime Louisville
  twitter: MaptimeLouisville
  #disqus: YOUR DISQUS USERNAME
